In [2]:
from sklearn.datasets import load_digits
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
digits=load_digits()


In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3)


In [6]:
lr=LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

C:\Users\Student\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9666666666666667

In [7]:
svm=SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.987037037037037

In [8]:
rf=RandomForestClassifier()
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9722222222222222

In [9]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)
    

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [10]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)


In [19]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)
scores_logistic=[]
scores_svm=[]
scores_rf=[]
for train_index, test_index in folds.split(digits.data, digits.target):
    x_train,x_test,y_train,y_test=digits.data[train_index], digits.data[test_index], digits.target[train_index],digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(), x_train,x_test,y_train,y_test))
    scores_svm.append(get_score(SVC(), x_train,x_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(), x_train,x_test,y_train,y_test))

C:\Users\Student\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Student\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_i

In [20]:
scores_logistic

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [21]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [22]:
scores_rf

[0.9348914858096828, 0.9532554257095158, 0.9332220367278798]

In [23]:
np.average(scores_rf)

0.9404563160823596

In [25]:
np.average(scores_logistic)

0.9265442404006677

In [26]:
np.average(scores_svm)

0.9699499165275459

In [27]:
from sklearn.model_selection import cross_val_score



In [28]:
cross_val_score(LogisticRegression(),digits.data,digits.target,cv=3)

C:\Users\Student\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Student\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_i

array([0.92153589, 0.94156928, 0.91652755])

In [29]:
cross_val_score(SVC(),digits.data,digits.target,cv=3)

array([0.96494157, 0.97996661, 0.96494157])

In [30]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target,cv=3)

array([0.93155259, 0.95659432, 0.92320534])